'use strict';

const fs = require('node:fs');
const path = require('node:path');
const utils = require('../js/utils');

const DATA_DIR = path.resolve(__dirname, '..', 'data');
const SOURCE_FILES = [
  ['spotify_me', 'me', 'Você', 'spotify', 'personal'],
  ['deezer', 'deezer', 'Deezer', 'cyan', 'chart'],
  ['itunes', 'itunes', 'iTunes', 'coral', 'chart']
];

function readSource(file, id, name, color, kind) {
  const full = path.join(DATA_DIR, `${file}.json`);
  if (!fs.existsSync(full)) throw new Error(`Arquivo obrigatório ausente: data/${file}.json`);
  let value;
  try { value = JSON.parse(fs.readFileSync(full, 'utf8')); } catch (error) { throw new Error(`JSON inválido em data/${file}.json.`); }
  const items = Array.isArray(value) ? value : value && value.items;
  if (!Array.isArray(items)) throw new Error(`Schema inválido em data/${file}.json: items deve ser array.`);
  const normalized = utils.dedupeByKey(items).map((item, position) => {
    if (!item || typeof item.title !== 'string' || typeof item.artist !== 'string') throw new Error(`Item inválido em data/${file}.json.`);
    return { key: utils.normalizeKey(item.title, item.artist), title: item.title, artist: item.artist, position };
  });
  return { id, name, color, kind, items: normalized };
}

function buildSnapshot() {
  const sources = SOURCE_FILES.map((definition) => readSource(...definition));
  return { generatedAt: new Date().toISOString(), sources };
}

function reportMatchRate(sources, logger = console.log) {
  const results = [];
  for (let i = 0; i < sources.length; i += 1) for (let j = i + 1; j < sources.length; j += 1) {
    const common = utils.intersectByKey(sources[i].items, sources[j].items).size;
    const sufficient = common >= 15;
    const pair = `${sources[i].id} x ${sources[j].id}`;
    results.push({ pair, common, sufficient });
    logger(`match-rate ${pair}: ${common} item(ns) comuns${sufficient ? '' : ' — INTERSEÇÃO INSUFICIENTE (<15)'}`);
  }
  return results;
}

function writeSnapshot(snapshot, output = path.join(DATA_DIR, 'snapshot.js')) {
  const json = JSON.stringify(snapshot, null, 2);
  const text = `/* Generated by scripts/build_snapshot.js. Do not edit. */\nwindow.RANK_SNAPSHOT = ${json};\n`;
  const temporary = `${output}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, text, { mode: 0o600 });
  fs.renameSync(temporary, output);
  return output;
}

if (require.main === module) {
  try { const snapshot = buildSnapshot(); reportMatchRate(snapshot.sources); const output = writeSnapshot(snapshot); console.log(`Snapshot gerado: ${output}`); }
  catch (error) { console.error(`Snapshot não gerado: ${error.message}`); process.exitCode = 1; }
}

module.exports = { readSource, buildSnapshot, writeSnapshot, reportMatchRate };
